name: flutterdemo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  fluro: ^1.5.1
  shared_preferences: 0.5.6+3
  image_picker: ^0.6.5
  fluttertoast: ^3.1.3
  badges: ^1.1.1
  package_info: ^0.4.0+17
  #轮播图
  flutter_banner_swiper: ^0.1.4
  #下拉刷新
  pull_to_refresh: ^1.5.8
  device_info : ^0.2.0
  flutter_share_me: ^0.9.1
  webview_flutter : ^0.3.19+9
  #选择通讯录
  easy_contact_picker: ^0.0.2
  flutter_luban: any
  permission_handler: any
  url_launcher: ^5.4.1
  #  flutter_native_image: ^0.0.5
  #定位
  location: ^3.0.0
  flutter_secured_storage: ^1.0.4
  flutter_share_plugin: ^0.1.3+3

 # facebook_app_events: ^0.6.0

  flutterplugin3:
    path: plugins/flutter_plugin3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/img_start.png
    - images/img_auth_banner.png
    - images/img_auth1.png
    - images/img_auth2.png
    - images/img_auth3.png
    - images/img_auth4.png
    - images/img_identity.png
    - images/logo.png
    - images/bg.png
    - images/person.png
    - images/pwd.png
    - images/img_lxr.png
    - images/head.png
    - images/icon_bzzx.png
    - images/icon_lsdd.png
    - images/icon_nav_xiaoxi.png
    - images/bar_shouye.png
    - images/bar_wode.png
    - images/icon_sz.png
    - images/icon_wdyhq.png
    - images/icon_yqhy.png
    - images/userBg.png
    - images/icon_list_arrow.png
    - images/icon_nav_arrow.png
    - images/about_logo.png
    - images/icon_nav_share.png
    - images/pic.png
    - images/fb.png
    - images/link.png
    - images/twitter.png
    - images/whatsapp.png
    - images/illustration_hkjl.png
    - images/img_wiat.png
    - images/img_nook.png
    - images/img_isok.png
    - images/card.png
    - images/img_repay.png
    - images/img_failtop.png
    - images/refuse_bg.png
    - images/img_fksb.png
    - images/img_fksb_top.png
    - images/ic_gzzm.png


